English comments; restore_cmd reread WAL from ohter host on decompress error; cmd_cleanup_temout=4 hours, retry_cnt=1 from remote cleanup; add check for recieved file size

diff --git a/pg_archive2/archive_remote_cmd_2 b/pg_archive2/archive_remote_cmd_2
--- a/pg_archive2/archive_remote_cmd_2
+++ b/pg_archive2/archive_remote_cmd_2
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# archive_remote_cmd для запуска на archive серверах
-# Принимает wal'ы и сопутствующие файлы на хост, на котором вызван и на SYNC-HOST (если указан).
-# На SYNC-HOST вызывает сам себя, без REMOTE-COMPRESS, так как wal уже сжаты. 
+# archive_remote_cmd is executed on archive servers
+# Saves WALs and associated files to the host on which it is run and to the SYNC-HOST (if it’s set).
+# At SYNC-HOST executes itself, without REMOTE-COMPRESS, as WALs have been already compressed.
 
 set -e
 set -o pipefail
@@ -19,32 +19,53 @@ remote_cmd=/usr/local/bin/archive_remote_cmd_2 # itslef
 dst_dir="$1"
 fname_org="$2"
 ftime="$3"
-remote_compress="$4"
+skip_compress="$4"
 pmax="$5"
 cluster_name="$6"
 sync_host="$7"        # second wal archive server hostname
+fsize="$8"            # source file size
 fname=$fname_org
 tmp_dir="/lib/init/rw/pg_recv_sb/$cluster_name" # tmpfs for wals
 
-# опции для отправки файла на следующий archive host
-cmd_timeout="6"   # аргумент для утилиты timeout (ssh и принимающий cat)
+# options for sending WAL to second archive host
+cmd_timeout="6"   # timeout  parameter for ssh, cat
 ssh_timeout_options="-o ConnectTimeout=10 -o ServerAliveInterval=6 -o ServerAliveCountMax=5"
 ssh_options="-o Compression=no -c aes128-gcm@openssh.com -o BatchMode=yes ${ssh_timeout_options}"
 ssh_master_socket='/tmp/ssh_%h_%p_%r'
 ssh_master_options='-o ControlMaster=auto -o ControlPersist=yes'
 ssh_options="$ssh_options -o ControlPath=$ssh_master_socket $ssh_master_options"
-cooldown_time="600" # не пытаться отправлять $cooldown_time секунд файлы на $sync_host после ошибки
+cooldown_time="600" # don’t try to send files to  $sync_host  after an error during $cooldown_time seconds
 
-if [ -z "$dst_dir" -o -z "$fname" -o -z "$cluster_name" ]; then
-    echo -e "usage: archive_remote_cmd DST-DIR DST-WAL-FILENAME SRC-FILE-TIMESTAMP REMOTE-COMPRESS PMAX CLUSTER-NAME [SYNC-HOST]\n" \
-        "\n" \
-        "DST-DIR                    - archive directory for WALs\n" \
-        "DST-WAL-FILENAME           - %f (file name)\n" \
-        "SRC-FILE-TIMESTAMP         - date and time of src WAL file in 'touch --date' format\n" \
-        "REMOTE-COMPRESS            - received WAL is not compressed, compress it here\n" \
-        "PMAX                       - if REMOTE-COMPRESS - use PMAX compress threads\n" \
-        "CLUSTER-NAME               - unique cluster name\n" \
-        "[SYNC-HOST]                - host to mirror WAL (upload via ssh)\n"
+recv_checked() {
+    local timeout=$1
+    local fname=$2
+    local fsize=$3
+    local res=0
+    local received
+
+    timeout "${timeout}" cat > "$fname" || res=$?
+    received=$(stat -c '%s' "$fname")
+
+    # zero file size not supported
+    if (( res || ! received || received != fsize )); then
+        mv "$fname" "$fname".bad
+        echo "ERROR: $fname.bad size $received, expected $fsize bytes, cat exit $res"
+        exit 1
+    fi
+}
+
+if [ -z "$dst_dir" -o -z "$fname" -o -z "$cluster_name" -o -z "$fsize" ]; then
+    cat <<'EOF'
+usage: archive_remote_cmd DST-DIR DST-WAL-FILENAME SRC-FILE-TIMESTAMP SKIP-COMPRESS PMAX CLUSTER-NAME SYNC-HOST SIZE
+DST-DIR                    - archive directory for WALs
+DST-WAL-FILENAME           - %f (file name)
+SRC-FILE-TIMESTAMP         - date and time of src WAL file in 'touch --date' format
+SKIP-COMPRESS              - received file is compressed, skip compress it
+PMAX                       - if SKIP-COMPRESS empty - use PMAX compress threads
+CLUSTER-NAME               - unique cluster name
+SYNC-HOST                  - host to mirror WAL (upload via ssh), may be empty
+SIZE                       - source file size for check receive
+EOF
     exit 1
 fi
 
@@ -56,21 +77,18 @@ if ! [ -d "$tmp_dir" ]; then
     mkdir -p "$tmp_dir"
 fi
 
-# не перезаписываем ранее сохраненные файлы с неверным md5
+# don’t overwrite previously saved files with wrong md5
 if [ -f "$tmp_dir"/"$fname_org".bad_md5 ]; then
     echo "ERROR: $dst_dir/$fname_org already exist with different md5"
     exit 1
 fi
 
-# если такой WAL уже есть в архиве, попробовать сравнить его md5
-# это нужно при promote, так как postgres из-за недоработки
-# пытается со standby после его promote повторно отправить
-# в архив WALы, которые уже там есть с предыдущего мастера
+# if there is the same WAL file in archchive, check md5
 if [ -f "$dst_dir"/"$fname_org" ] && [ "$fname_org" != "LASTLOG" ]; then
-    timeout ${cmd_timeout} cat > "$tmp_dir"/"$fname_org".dup
+    recv_checked "${cmd_timeout}" "$tmp_dir"/"$fname_org".dup "$fsize"
     md5_dup=`md5sum "$tmp_dir"/"$fname_org".dup | awk '{print $1}'`
-    if [[ $fname == ???????????????????????? && $remote_compress ]]; then
-        # возьмем оригинал из архива и распакуем для проверки md5
+    if [[ $fname == ???????????????????????? && ! $skip_compress ]]; then
+        # uncompress file from archive to compare its md5 value
         pbzip2 -d -p"$pmax" < "$dst_dir"/"$fname_org" > "$tmp_dir"/"$fname_org".org
         md5_orig=`md5sum "$tmp_dir"/"$fname_org".org | awk '{print $1}'`
         rm "$tmp_dir"/"$fname_org".org
@@ -79,12 +97,12 @@ if [ -f "$dst_dir"/"$fname_org" ] && [ "$fname_org" != "LASTLOG" ]; then
     fi
     if [[ $md5_orig != $md5_dup ]]; then
         echo "ERROR: $dst_dir/$fname_org already exist with different md5"
-        # пожатый дубликат с другим md5 оставляем для анализа
+        # save the compressed copy with another md5 value for analyze purpose
         mv "$tmp_dir"/"$fname_org".dup "$tmp_dir"/"$fname_org".bad_md5
         touch --no-create --date "$ftime" "$tmp_dir"/"$fname_org".bad_md5 || true # ignore errors
         exit 1
     else
-        # если md5 совпадает, то выходим без ошибки
+        # if md5 values do not match, then exit without error
         echo "WARN: $dst_dir/$fname_org already exist with same md5"
         rm "$tmp_dir"/"$fname_org".dup
         exit 0
@@ -96,52 +114,48 @@ if [ -f "$dst_dir"/"$fname".tmp ]; then
     exit 1
 fi
 
-# что бы не обрабатывать ошибки при восстановлении от частично прочитанного файла
-# который в данный момент ещё пишется в архив, будем создавать файл в архиве атомарно
-# через move
-if [[ $fname == ???????????????????????? && $remote_compress ]]; then
-    timeout ${cmd_timeout} cat > "$tmp_dir"/"$fname".new
-    size=$(stat -c '%s' "$tmp_dir"/"$fname".new)
-    if [[ $size -ne 16777216 ]]; then
-        mv "$tmp_dir"/"$fname".new "$tmp_dir"/"$fname".bad
-        echo "ERROR: $tmp_dir/$fname.bad wrong size: $size"
-        exit 1
-    fi
+# to skip errors of recovering partial file
+# which is being archived (still in progress), let’s atomary create file in archive
+# with the help of move
+if [[ $fname == ???????????????????????? && ! $skip_compress ]]; then
+    recv_checked "${cmd_timeout}" "$tmp_dir"/"$fname".new "$fsize"
     pbzip2 -1 -p"$pmax" < "$tmp_dir"/"$fname".new > "$dst_dir"/"$fname".tmp
     rm "$tmp_dir"/"$fname".new
 else
-    timeout ${cmd_timeout} cat > "$dst_dir"/"$fname".tmp
+    recv_checked "${cmd_timeout}" "$dst_dir"/"$fname".tmp "$fsize"
 fi
 
 touch --no-create --date "$ftime" "$dst_dir"/"$fname".tmp || true # ignore errors
 
-# наконец, кладем файл в директорию назначения на текущем хосте
 mv "$dst_dir"/"$fname".tmp "$dst_dir"/"$fname"
 
-# fsync файла и директории, в случае если установлен пакет 'coreutils-sync'
+#If 'coreutils-sync' is installed, fsync file and folder
 if [ -f "/usr/local/bin/sync" ]; then
     /usr/local/bin/sync "$dst_dir"/"$fname"
     /usr/local/bin/sync "$dst_dir"
+else
+    sync "$dst_dir"/"$fname"
+    sync "$dst_dir"
 fi
 
-# проверим настало ли время пытаться отправить файл на зеркалирующий архив
-# (прошло ли $cooldown_time секунд с момента последней ошибки отправки файла)
+# check if it the time to start retrying writing to second archive ($cooldown_time passed)
 if [ -f "${tmp_dir}"/"sync_wal_error_flag" ]; then
     now_time=$(date +%s)
     last_err_time=$(stat -c%Y "${tmp_dir}"/"sync_wal_error_flag")
-
-    # если с момента последней ошибки не прошло $cooldown_time секунд,
-    # то не пытаемся "зеркалировать" файл на второй архив-сервер
     if [[ $(( $now_time - $last_err_time)) -le $cooldown_time ]]; then
         sync_host=
     fi
 fi
-# пытаемся отправить файл на второй архив-сервер
+# try to transfer file to second archive
 if ! [ -z "$sync_host" ]; then
+    size_compressed=$(stat -c '%s' "$dst_dir"/"$fname")
     set +e
     exit_code=0
-    timeout ${cmd_timeout} cat "$dst_dir"/"$fname" | \
-        timeout ${cmd_timeout} ssh $ssh_options "$sync_host" "$remote_cmd" "$dst_dir" "$fname" "'$ftime'" "''" "$pmax" "$cluster_name"
+    timeout ${cmd_timeout} cat "$dst_dir"/"$fname"                              \
+        | timeout ${cmd_timeout} ssh $ssh_options "$sync_host" "$remote_cmd"    \
+                  "$dst_dir" "$fname" "'$ftime'"                                \
+                  "'skip'" "$pmax" "$cluster_name"                              \
+                  "''" "'$size_compressed'"
     exit_code=$?
     set -e
     if [[ $exit_code -ne 0 ]] ; then
diff --git a/pg_archive2/restore_cmd_2 b/pg_archive2/restore_cmd_2
--- a/pg_archive2/restore_cmd_2
+++ b/pg_archive2/restore_cmd_2
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# в цикле пытается получить указанный wal/файл из src_hosts
+# try to get specific WAL file from src_hosts in cycle
 set -e
 
 error_handler() {
@@ -10,16 +10,18 @@ error_handler() {
 }
 trap error_handler ERR
 
+saved_args=( "$@" )
+saved_self_name=$0
 pmax=4
-local_dir=/var/local/WALs  # для ручного подкладывания wal
+local_dir=/var/local/WALs  # for putting wal manually
 only_local=                # use WALs only from local_dir, do not read it from NFS
 
 src_hosts="$1" # ssh hosts
-buffer_dir=/var/lib/postgresql/wals_buffer      # сначала загружаем файл по ssh сюда, не tmpfs
+buffer_dir=/var/lib/postgresql/wals_buffer      # first load file by ssh here, not tmpfs
 
-tmp_dir='/lib/init/rw/pg_recv_sb'               # файлы с счетчиком ошибок, создается puppet, tmpfs
+tmp_dir='/lib/init/rw/pg_recv_sb'               # file wiht error counter, created by puppet, tmpfs
 
-cmd_timeout="6"   # аргумент для утилиты timeout (ssh запускаем через нее)
+cmd_timeout="6"
 ssh_timeout_options="-o ConnectTimeout=10 -o ServerAliveInterval=6 -o ServerAliveCountMax=5"
 ssh_options="-o Compression=no -c aes128-gcm@openssh.com -o BatchMode=yes ${ssh_timeout_options}"
 ssh_master_socket='/tmp/ssh_%h_%p_%r'
@@ -28,7 +30,7 @@ use_ssh_persist=yes
 
 src_dir="$2"
 fname="$3"
-dst_file="$4"    # всегда называется 'pg_xlog/RECOVERYXLOG'
+dst_file="$4"    # always 'pg_xlog/RECOVERYXLOG'
 delay_time="$5"  # wal apply delay
 
 retry_count="6"     # see below
@@ -57,19 +59,21 @@ decompress() {
     local dst_file=$1
     mime=$(file -m /etc/postgresql-common/compress.mime.mgc -b --mime-type "$dst_file")
     if [ "$mime" = "application/x-bzip2" ]; then
-        pbzip2 -p"$pmax" -d < "$dst_file" > "$dst_file".bz2-tmp
+        pbzip2 -p"$pmax" -d < "$dst_file" > "$dst_file".bz2-tmp || { decompress_error=$?; return 1; }
         mv "$dst_file".bz2-tmp "$dst_file"
     elif [ "$mime" = "application/x-gzip" ]; then
-        gunzip < "$dst_file" > "$dst_file".gz-tmp
+        gunzip < "$dst_file" > "$dst_file".gz-tmp || { decompress_error=$?; return 1; }
         mv "$dst_file".gz-tmp "$dst_file"
     fi
 }
 
-# решает применять текущий wal или нет из директории-буфера
+# decides whether to apply current wal from buffer or not
 apply_wal() {
-    local src_dir=$1
-    local fname=$2
-    local dst_file=$3
+    local received_from=$1
+    local src_dir=$2
+    local fname=$3
+    local dst_file=$4
+    local decompress_error
 
     if [ "$delay_time" ] && [ "$delay_time" -gt 0 ]; then
         ftime="$(stat -c %Y "$src_dir"/"$fname")"
@@ -85,7 +89,30 @@ apply_wal() {
     fi
 
     mv "$src_dir"/"$fname" "$dst_file"
-    decompress "$dst_file"
+    decompress_error=''
+    if ! decompress "$dst_file"; then
+        # dst_file can be «destroyed» during decompress,
+        # that's why ignore possible error when delete it
+        rm "$dst_file" || true
+
+        # if error, try another host, only if it is not local operation
+        # not local_dir or buffer_dir
+        if (( decompress_error )) && [[ $received_from ]]; then
+            if [[ $RESTORE_CMD_TRY_OTHER ]]; then
+                echo "ERROR: cannot unpack wal from all hosts"
+                exit 1
+            fi
+
+            # reexec and try other server
+            echo "WARNING: decompress error from host $received_from, trying other"
+            RESTORE_CMD_TRY_OTHER=$received_from \
+                exec "$saved_self_name" "${saved_args[@]}"
+        else
+            # mv error or something unknown
+            echo "ERROR: decompress error"
+            exit 1
+        fi
+    fi
 }
 
 if [ -d "$local_dir" ] && [ -f "$local_dir"/"$fname" ]; then
@@ -96,7 +123,7 @@ if ! [ -d "$buffer_dir" ]; then
     mkdir -p "$buffer_dir"
 fi
 
-# проверяем что файл существует и его размер не равен 0
+# check that wal file exists and its size is not zero
 if [ -s "$buffer_dir"/"$fname" ]; then
     src_dir="$buffer_dir"
 fi
@@ -115,59 +142,65 @@ fi
 src_hosts_count=$(wc -w <<< $src_hosts)
 
 # fetch wal via ssh to buffer dir
-fetch_errors=0 # любые ошибки получения wal
-conn_errors=0  # только ошибки копирования wal по ssh
+fetch_errors=0 # any receiving wal errors
+conn_errors=0  # only ssh transfer errors
 for host in $src_hosts ; do
-    # сначала проверяем нужно ли делать попытку для данного хоста
+    # if it is retry and this is the host from which corrupted wal had been received, then try another host
+    if [[ $RESTORE_CMD_TRY_OTHER && $host = $RESTORE_CMD_TRY_OTHER ]]; then
+        fetch_errors=$(($fetch_errors + 1))
+        continue
+    fi
+
+    # check if retry is nedeed for that host
     if [ -f "${tmp_dir}/ssh-errors_${host}_" ]; then
-        # если не достигли $retry_count, то продолжаем пытаться читать с данного хоста
+        # if not reached $retry_count limit, then continue to read from that host
         was_failed_cnt=$(<"${tmp_dir}/ssh-errors_${host}_")
         if [ "$was_failed_cnt" -lt "$retry_count" ]; then
             true
-        # при достижении $retry_count попыток ssh, перестаем пытаться прочитать wal с хоста $cooldown_time секунд
+        # reaching $retry_count retries limit, stop try to read wal from that host during $cooldown_time seconds
         else
             now_time=$(date +%s)
             last_err_time=$(stat -c%Y "${tmp_dir}/ssh-errors_${host}_")
             if [[ $(( $now_time - $last_err_time)) -le $cooldown_time ]]; then
                 fetch_errors=$(($fetch_errors + 1))
-                # попытаемся прочитать со следующего хоста
+                # try to read from next host
                 continue
-            # начинаем заново пытаться после $cooldown_time, сбросив счетчик ошибок хоста
+            # repeat again trying after $cooldown_time, with setting counter of errors to 0
             else
                 rm "${tmp_dir}/ssh-errors_${host}_"
             fi
         fi
     fi
 
-    # читаем файл через ssh
-    # в случае ошибки, создаст файл нулевого размера (!)
+    # read by ssh
+    # in case of error, empty file will be created (!)
     set +e
     timeout ${cmd_timeout} ssh ${ssh_options} ${host} \
         "test -f '$src_dir'/'$fname' && cat '$src_dir'/'$fname' || exit 148" \
                       > "$buffer_dir"/"$fname".part
     ssh_code=$?
     set -e
-    # выходим из цикла, если удалось забрать файл
+    # if successfully get file then exit
     if [ "$ssh_code" -eq "0" ]; then
-        # при успехе, сбрасываем счетчик ошибок, удалив файл счетчика
+        # in case of success, set error counter value to 0 by removing file with counter
         [ -f "${tmp_dir}/ssh-errors_${host}_" ] && rm "${tmp_dir}/ssh-errors_${host}_"
         mv "$buffer_dir"/"$fname".part "$buffer_dir"/"$fname"
         break;
-    # файла еще нет на архив-сервере
+    # file still not exist on archive server
     elif [ "$ssh_code" -eq "148" ]; then
-        echo "ERROR: can't find wal '$fname' at host '$host'"
-        # сбрасываем файл-счетчик ошибок, так как связь есть/восстановлена
+        echo "WARNING: can't find wal '$fname' at host '$host'"
+        # zero the file-counter, as connection is restored
         [ -f "${tmp_dir}/ssh-errors_${host}_" ] && rm "${tmp_dir}/ssh-errors_${host}_"
         fetch_errors=$(($fetch_errors + 1))
-        # удаляем пустой временный файл (size 0)
+        # delete empty temp file
         test -f "$buffer_dir"/"$fname".part && rm "$buffer_dir"/"$fname".part
-    # все остальные коды выхода считаем ошибкой соединения
+    # all other exit codes are considered to be connection error
     else
-        echo "ERROR: connection error, can't fetch wal '$fname' from host '$host'"
+        echo "WARNING: connection error, can't fetch wal '$fname' from host '$host'"
         fetch_errors=$(($fetch_errors + 1))
         conn_errors=$(($conn_errors + 1))
 
-        # инкрементируем файл-счетчик ошибок соединения с хостом
+        # increment counter of connection errors
         if [ -f "${tmp_dir}/ssh-errors_${host}_" ]; then
             failed_cnt=$(<"${tmp_dir}/ssh-errors_${host}_")
             failed_cnt=$(( failed_cnt + 1 ))
@@ -175,13 +208,13 @@ for host in $src_hosts ; do
         else
             echo 1 > "${tmp_dir}/ssh-errors_${host}_"
         fi
-        # удаляем пустой временный файл (size 0)
+        # remove empty temp file (size 0)
         test -f "$buffer_dir"/"$fname".part && rm "$buffer_dir"/"$fname".part
     fi
 done
+received_from=$host
 
-# если не удалось подключиться к обоим хостам, то удаляем их файлы-счетчики ошибок,
-# чтобы не "уснуть" зря и надолго
+# if can't connect to both hosts, then remove files counters of errors, то удаляем их файлы-счетчики ошибок,
 if [ "$conn_errors" -ge "$src_hosts_count" ]; then
     for host in $src_hosts ; do
         if [ -f "${tmp_dir}/ssh-errors_${host}_" ]; then
@@ -195,7 +228,7 @@ if [ "$fetch_errors" -ge "$src_hosts_count" ]; then
     exit 1
 fi
 
-apply_wal "$buffer_dir" "$fname" "$dst_file"
+apply_wal "$received_from" "$buffer_dir" "$fname" "$dst_file"
 
 exit 0
 
diff --git a/pg_archive2/wal-cleanup_2 b/pg_archive2/wal-cleanup_2
--- a/pg_archive2/wal-cleanup_2
+++ b/pg_archive2/wal-cleanup_2
@@ -13,6 +13,8 @@ PG_ARCHIVECLEANUP_LOG_REMOTE="/var/tmp/wal-cleanup-pg_archivecleanup_REMOTE_${PG
 
 # опции для проверки последнего нужного wal на зеркалирующем archive хосте и удаленного cleanup
 cmd_timeout="1200"   # аргумент для утилиты timeout (ssh)
+cmd_cleanup_timeout=$((4 * 60 * 60))  # аргумент для утилиты timeout (ssh) при вызове pg_archivecleanup для непосредственно очистки
+retry_cnt=1
 ssh_timeout_options="-o ConnectTimeout=10 -o ServerAliveInterval=6 -o ServerAliveCountMax=5"
 ssh_options="-o Compression=no -c aes128-gcm@openssh.com -o BatchMode=yes ${ssh_timeout_options}"
 ssh_master_socket='/tmp/ssh_%h_%p_%r'
@@ -29,108 +31,138 @@ function usage() {
     echo "usage: wal-cleanup /path/to/walshipping/src_backup /path/to/walshipping/logs REMOTE-ARCHIVE-HOST"
 }
 
+function say() {
+    echo $(date +'%F %T') "$@"
+}
+
 if [ -z "$SRC_DIR" -o -z "$WALS_DIR" -o -z "$REMOTE_ARCHIVE" ]; then
     usage
     exit 1
 fi
 
-LOCK_FILE="$WALS_DIR/../$LOCK_FILE_NAME"
+LOCK_FILE=$(readlink -f "$WALS_DIR/../$LOCK_FILE_NAME")
 
-if [ -f "$LOCK_FILE" ]; then
-    echo "lock file '$LOCK_FILE' from $(date -r "$LOCK_FILE") exists, abort"
-    exit 1
-fi
+set -e # check redirect
 
-date +%s > "$LOCK_FILE"
-exec 3>&1 > "$LOG_FILE" 2>&1
-trap "cat \"$LOG_FILE\" >&3; rm -f \"$LOCK_FILE\";" EXIT
+main () {
+    set +e # redirect checked
 
-echo $(date +'%F %T') "start wal-cleanup: '$SRC_DIR' '$WALS_DIR'"
+    flock -n 9 || { echo "lock file '$LOCK_FILE' from $(< "$LOCK_FILE") locked, abort"; exit 1; }
+    { echo -n "$$ "; date +'%F %T'; } > "$LOCK_FILE"
 
-if [ ! -r "$SRC_DIR"/backup_label ]; then
-    echo "cannot read LOCAL $SRC_DIR/backup_label, abort"
-    exit 1
-fi
+    exec 3>&1 > "$LOG_FILE" 2>&1
+    trap "cat \"$LOG_FILE\" >&3" EXIT
 
-LAST_NEEDED_WAL_LOCAL=$(grep 'START WAL LOCATION.\+(file .\+)' "$SRC_DIR"/backup_label 2> /dev/null | sed -e 's/.\+(file \(.\+\))/\1/')
-echo "LOCAL backup label: '$SRC_DIR/backup_label', last LOCAL needed wal: '$WALS_DIR/$LAST_NEEDED_WAL_LOCAL'"
+    say "start wal-cleanup: '$SRC_DIR' '$WALS_DIR'"
 
-if [ -z "$LAST_NEEDED_WAL_LOCAL" ]; then
-    echo "cannot find last needed LOCAL wal, abort"
-    exit 1
-fi
+    if [ ! -r "$SRC_DIR"/backup_label ]; then
+        echo "cannot read LOCAL $SRC_DIR/backup_label, abort"
+        exit 1
+    fi
 
-if [ ! -f "$WALS_DIR"/"$LAST_NEEDED_WAL_LOCAL" ]; then
-    echo "something wrong, last needed LOCAL wal not exists, abort"
-    exit 1
-fi
+    LAST_NEEDED_WAL_LOCAL=$(grep 'START WAL LOCATION.\+(file .\+)' "$SRC_DIR"/backup_label 2> /dev/null | sed -e 's/.\+(file \(.\+\))/\1/')
+    echo "LOCAL backup label: '$SRC_DIR/backup_label', last LOCAL needed wal: '$WALS_DIR/$LAST_NEEDED_WAL_LOCAL'"
 
-# проверим существует ли backup_label на удаленном сервере и убедимся, что это точно не ошибка ssh
-no_remote_backup_label=$(timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "test -f \"$CWD/$SRC_DIR\"/backup_label || echo 'no backup label'")
-if [ "$no_remote_backup_label" = "no backup label" ]; then
-    # если backup_label нет, LAST_NEEDED_WAL_OLDEST будем читать из локального backup_label (ниже)
-    echo "WARNING: backup_label at REMOTE host '$REMOTE_ARCHIVE' does not exist. No backups?"
-    LAST_NEEDED_WAL_REMOTE="GGGGGGGGGGGGGGGGGGGGGGGG"
-else
-    # по ssh считываем backup_label на зеркалирующем архиве
-    LAST_NEEDED_WAL_REMOTE=$(timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "grep 'START WAL LOCATION.\+(file .\+)' \"$CWD/$SRC_DIR\"/backup_label | sed -e 's/.\+(file \(.\+\))/\1/'")
-fi
+    if [ -z "$LAST_NEEDED_WAL_LOCAL" ]; then
+        echo "cannot find last needed LOCAL wal, abort"
+        exit 1
+    fi
 
-if [[ "$LAST_NEEDED_WAL_REMOTE" != ???????????????????????? ]]; then
-    echo "something wrong, can't read last needed REMOTE wal"
-    exit 1
-else
-    echo "REMOTE backup label: '$SRC_DIR/backup_label', last REMOTE needed wal: '$WALS_DIR/$LAST_NEEDED_WAL_REMOTE'"
-fi
+    if [ ! -f "$WALS_DIR"/"$LAST_NEEDED_WAL_LOCAL" ]; then
+        echo "something wrong, last needed LOCAL wal not exists, abort"
+        exit 1
+    fi
 
-# выбираем самый старый wal
-if [[ "$LAST_NEEDED_WAL_LOCAL" < "$LAST_NEEDED_WAL_REMOTE" ]]; then
-    LAST_NEEDED_WAL_OLDEST=$LAST_NEEDED_WAL_LOCAL
-else
-    LAST_NEEDED_WAL_OLDEST=$LAST_NEEDED_WAL_REMOTE
-fi
+    # check if backup_label on remote server exists and check that there is no ssh error
+    no_remote_backup_label=$(timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "test -f \"$CWD/$SRC_DIR\"/backup_label || echo 'no backup label'")
+    if [ "$no_remote_backup_label" = "no backup label" ]; then
+        # if  there is no backup_label, read LAST_NEEDED_WAL_OLDEST from local backup_label
+        echo "WARNING: backup_label at REMOTE host '$REMOTE_ARCHIVE' does not exist. No backups?"
+        LAST_NEEDED_WAL_REMOTE="GGGGGGGGGGGGGGGGGGGGGGGG"
+    else
+        # with the help of ssh read backup_label
+        LAST_NEEDED_WAL_REMOTE=$(timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "grep 'START WAL LOCATION.\+(file .\+)' \"$CWD/$SRC_DIR\"/backup_label | sed -e 's/.\+(file \(.\+\))/\1/'")
+    fi
 
-echo "oldest needed wal is: '$LAST_NEEDED_WAL_OLDEST'"
+    if [[ "$LAST_NEEDED_WAL_REMOTE" != ???????????????????????? ]]; then
+        echo "something wrong, can't read last needed REMOTE wal"
+        exit 1
+    else
+        echo "REMOTE backup label: '$SRC_DIR/backup_label', last REMOTE needed wal: '$WALS_DIR/$LAST_NEEDED_WAL_REMOTE'"
+    fi
 
-echo "##############################"
-echo "LOCAL dry-run of pg_archivecleanup"
-echo "$PGTOOLS"/pg_archivecleanup -n "$WALS_DIR" "$LAST_NEEDED_WAL_OLDEST"
-date > "$PG_ARCHIVECLEANUP_LOG_LOCAL"
-"$PGTOOLS"/pg_archivecleanup -n "$WALS_DIR" "$LAST_NEEDED_WAL_OLDEST" | sort >> "$PG_ARCHIVECLEANUP_LOG_LOCAL"
-echo will be cleaned \~ $(($(wc -l "$PG_ARCHIVECLEANUP_LOG_LOCAL" | cut -d' ' -f1) - 1)) WALs
-echo '---'
-head -3 "$PG_ARCHIVECLEANUP_LOG_LOCAL"
-echo . . .
-tail -2 "$PG_ARCHIVECLEANUP_LOG_LOCAL"
-echo '---'
+    # choose the oldest WAL
+    if [[ "$LAST_NEEDED_WAL_LOCAL" < "$LAST_NEEDED_WAL_REMOTE" ]]; then
+        LAST_NEEDED_WAL_OLDEST=$LAST_NEEDED_WAL_LOCAL
+    else
+        LAST_NEEDED_WAL_OLDEST=$LAST_NEEDED_WAL_REMOTE
+    fi
 
-echo "##############################"
-echo "REMOTE dry-run of pg_archivecleanup"
-date > "$PG_ARCHIVECLEANUP_LOG_REMOTE"
-echo timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "\"$PGTOOLS\"/pg_archivecleanup -n \"$CWD/$WALS_DIR\" \"$LAST_NEEDED_WAL_OLDEST\""
-timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "\"$PGTOOLS\"/pg_archivecleanup -n \"$CWD/$WALS_DIR\" \"$LAST_NEEDED_WAL_OLDEST\"" | sort >> "$PG_ARCHIVECLEANUP_LOG_REMOTE"
-echo will be cleaned \~ $(($(wc -l "$PG_ARCHIVECLEANUP_LOG_REMOTE" | cut -d' ' -f1) - 1)) WALs
-echo '---'
-head -3 "$PG_ARCHIVECLEANUP_LOG_REMOTE"
-echo . . .
-tail -2 "$PG_ARCHIVECLEANUP_LOG_REMOTE"
-echo '---'
+    echo "oldest needed wal is: '$LAST_NEEDED_WAL_OLDEST'"
 
-# pg_archivecleanup не возвращает код ошибки при ошибке удаления WAL, а всегда возвращает 0, поэтому результат
-# выполнения pg_archivecleanup невозможно проверить... проверяем тут только ошибки существования каталога и
-# присутствие необходимых аргументов
-echo "Perform LOCAL pg_archivecleanup ..."
-if ! "$PGTOOLS"/pg_archivecleanup "$WALS_DIR" "$LAST_NEEDED_WAL_OLDEST"; then
-    echo "error from LOCAL pg_archivecleanup, abort"
-    exit 1
-fi
-echo "Perform REMOTE pg_archivecleanup ..."
-if ! timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "\"$PGTOOLS\"/pg_archivecleanup \"$CWD/$WALS_DIR\" \"$LAST_NEEDED_WAL_OLDEST\""; then
-    echo "error from LOCAL pg_archivecleanup, abort"
-    exit 1
-fi
+    echo "##############################"
+    echo "LOCAL dry-run of pg_archivecleanup"
+    echo "$PGTOOLS"/pg_archivecleanup -n "$WALS_DIR" "$LAST_NEEDED_WAL_OLDEST"
+    date > "$PG_ARCHIVECLEANUP_LOG_LOCAL"
+    "$PGTOOLS"/pg_archivecleanup -n "$WALS_DIR" "$LAST_NEEDED_WAL_OLDEST" | sort >> "$PG_ARCHIVECLEANUP_LOG_LOCAL"
+    echo will be cleaned \~ $(($(wc -l "$PG_ARCHIVECLEANUP_LOG_LOCAL" | cut -d' ' -f1) - 1)) WALs
+    echo '---'
+    head -3 "$PG_ARCHIVECLEANUP_LOG_LOCAL"
+    echo . . .
+    tail -2 "$PG_ARCHIVECLEANUP_LOG_LOCAL"
+    echo '---'
 
-echo $(date +'%F %T') "done wal-cleanup: '$SRC_DIR' '$WALS_DIR'"
+    echo "##############################"
+    echo "REMOTE dry-run of pg_archivecleanup"
+    date > "$PG_ARCHIVECLEANUP_LOG_REMOTE"
+    echo timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "\"$PGTOOLS\"/pg_archivecleanup -n \"$CWD/$WALS_DIR\" \"$LAST_NEEDED_WAL_OLDEST\""
+    timeout ${cmd_timeout} ssh $ssh_options $REMOTE_ARCHIVE "\"$PGTOOLS\"/pg_archivecleanup -n \"$CWD/$WALS_DIR\" \"$LAST_NEEDED_WAL_OLDEST\"" | sort >> "$PG_ARCHIVECLEANUP_LOG_REMOTE"
+    echo will be cleaned \~ $(($(wc -l "$PG_ARCHIVECLEANUP_LOG_REMOTE" | cut -d' ' -f1) - 1)) WALs
+    echo '---'
+    head -3 "$PG_ARCHIVECLEANUP_LOG_REMOTE"
+    echo . . .
+    tail -2 "$PG_ARCHIVECLEANUP_LOG_REMOTE"
+    echo '---'
+
+    # pg_archivecleanup don't return error code when there is an error in WAL delete operation, it always return 0, that is why
+    # result of pg_archivecleanup can't be checked
+    say "Perform LOCAL pg_archivecleanup ..."
+    if ! "$PGTOOLS"/pg_archivecleanup "$WALS_DIR" "$LAST_NEEDED_WAL_OLDEST"; then
+        echo "error from LOCAL pg_archivecleanup, abort"
+        exit 1
+    fi
+    for ((i = 0; i <= retry_cnt; i++)); do
+        say "Perform REMOTE pg_archivecleanup ..."
+        if ! timeout ${cmd_cleanup_timeout} \
+             ssh $ssh_options $REMOTE_ARCHIVE \
+             flock -nE 125 "$LOCK_FILE" "'$PGTOOLS'/pg_archivecleanup '$CWD/$WALS_DIR' '$LAST_NEEDED_WAL_OLDEST'"
+        then
+            res=${PIPESTATUS[0]}
+            if (( res == 124 )); then
+                if ((i != retry_cnt)); then
+                    msg="retrying ($((i+1)) of $retry_cnt)"
+                else
+                    msg="abort"
+                fi
+                echo "REMOTE pg_archivecleanup timeout, $msg"
+                continue
+            elif (( res == 125 )); then
+                echo "REMOTE pg_archivecleanup still running, abort"
+                exit 1
+            else
+                echo "error with REMOTE pg_archivecleanup, abort"
+                exit 1
+            fi
+        else
+            break
+        fi
+    done
+
+    say "done wal-cleanup: '$SRC_DIR' '$WALS_DIR'"
+
+} 9>> "$LOCK_FILE"
+
+main
 
 exit 0
 
