Update pg_archive to current version

diff --git a/pg_archive/archive_cmd b/pg_archive/archive_cmd
--- a/pg_archive/archive_cmd
+++ b/pg_archive/archive_cmd
@@ -3,11 +3,18 @@
 set -e
 pmax=4
 remote_cmd=/usr/local/bin/archive_remote_cmd
-ssh_options="-o Compression=no -c arcfour"
+ssh_options="-o Compression=no -c aes128-gcm@openssh.com -o BatchMode=yes"
 ssh_master_socket='/tmp/ssh_%h_%p_%r'
 ssh_master_options='-o ControlMaster=auto -o ControlPersist=yes'
 use_ssh_persist=
+remote_compress=
+send_status=
+pwals=5
+ready_wals_for_parallel=10   # ready wals должен быть, как минимум, в два раза больше, чем pwals ?
 
+unset LANG LANGUAGE LC_ALL LC_CTYPE LC_COLLATE LC_MESSAGES LC_TIME LC_NUMERIC
+export LC_ALL=C
+ 
 if [ -f /etc/default/archive_cmd ]; then
     . /etc/default/archive_cmd
 fi
@@ -18,8 +25,11 @@ fi
 
 dst_host="$1"
 dst_dir="$2"
+log_dir="$dst_dir"/../
 src_file="$3"
 fname="$4"
+src_dir=${src_file%/$fname}
+arch_status_dir="$src_dir"/archive_status
 
 if [ -z "$dst_host" -o -z "$dst_dir" -o -z "$src_file" -o -z "$fname" ]; then
     echo -e "usage: archive_cmd DST-HOSTNAME DST-DIR SRC-WAL-FILENAME-WITH-PATH SRC-WAL-FILENAME\n" \
@@ -33,15 +43,82 @@ fi
 
 set -o pipefail
 
-ftime=$(stat -c %y "$src_file")
-# проверить и архивировать только WAL, backup label пропускать без архивации
-if [[ "$fname" == ???????????????????????? ]]; then
-    pbzip2 -p"$pmax" < "$src_file"
-else
-    cat "$src_file"
-fi \
-    | ssh $ssh_options "$dst_host" "$remote_cmd" "$dst_dir" "$fname" "'$ftime'"
+# проверяет является ли имя файла именем wal
+is_wal() {
+    local fname="$1"
+    if [[ "$fname" == ???????????????????????? ]] && [[ "$fname" != *.* ]]; then
+        return 0 # zero is true
+    else
+        return 1 # non-zero is false
+    fi
+}
 
-/usr/local/bin/vmtouch -q -e "$src_file"
+# отправляет файл на standby по ssh
+send_wal() {
+    local fname_with_path="$1"
+    local file_name="$2"
+    ftime=$(stat -c %y "$fname_with_path")
+    # проверить и архивировать только WAL, backup label и history пропускать без архивации
+    if [[ "$file_name" == ???????????????????????? && -z "$remote_compress" ]]; then
+        pbzip2 -1 -p"$pmax" < "$fname_with_path"
+    else
+        cat "$fname_with_path"
+    fi \
+        | ssh $ssh_options "$dst_host" "$remote_cmd" "$dst_dir" "$file_name" "'$ftime'" "'$remote_compress'" "$pmax" "'$send_status'"
+    /usr/local/bin/vmtouch -q -e "$fname_with_path"
+}
+
+# проверим не отправлялся ли такой файл уже в архив
+if [[ -r ${log_dir}/LASTLOG ]]; then
+    prev_archived=$(< ${log_dir}/LASTLOG)
+else
+    prev_archived=""
+fi
+# файлы вида '000000010004EF04000000E1.00010DF0.backup' и '00000015.history' архивируем всегда
+# сравниваем только wal
+# если предыдущий заархивированный файл не wal - архивируем в один поток (для корректного сравнения '<')
+if is_wal "$fname" && is_wal "$prev_archived"; then
+    if [[ "$fname" < "$prev_archived" ]] || [[ "$fname" = "$prev_archived" ]]; then
+        echo "File '$fname' was already sent to archive. Skipping..."
+        exit 0
+    fi
+fi
+
+# нужно ли выполнить параллельное архивирование?
+ready_count=$(find ${arch_status_dir}/ -maxdepth 1 -type f -name "????????????????????????.ready" | wc -l)
+
+# архивируем в один поток если:
+# - число готовых к архивации wal меньше порога ready_wals_for_parallel
+# - файл не является wal (.backup, .history)
+# - предыдущий заархивированный файл не является wal
+if [[ $ready_count -le $ready_wals_for_parallel ]] || ! is_wal "$fname" || ! is_wal "$prev_archived"; then
+    send_wal "$src_file" "$fname"
+    wal=$fname
+else
+    # запускаем параллельное архивирвоание
+
+    # возьем pwals файлов
+    ready_wals=$(find ${arch_status_dir}/ -maxdepth 1 -type f -name "????????????????????????.ready" -printf '%f\n'\
+                        | sort | grep -A "$(( pwals - 1 ))" -F ${fname})
+
+    # отправим эти wal параллельно
+    declare -A send_pids
+    for wal_ready in $ready_wals ; do
+        wal=${wal_ready%.ready}
+        send_wal "$src_dir"/"$wal" "$wal" & send_pids[$wal]=$!
+    done
+
+    # обработаем все коды выхода каждого потока
+    for wal_pid in ${!send_pids[@]}; do
+        exit_code=0
+        wait ${send_pids[$wal_pid]} || exit_code=$?
+        if [[ $exit_code -ne 0 ]] ; then
+            echo "ERROR: can't send '$wal_pid' to archive. Exit code: '$exit_code'"
+            exit 1
+        fi
+    done
+fi
+
+echo "$wal" > "$log_dir"/LASTLOG
 
 exit 0
diff --git a/pg_archive/archive_remote_cmd b/pg_archive/archive_remote_cmd
--- a/pg_archive/archive_remote_cmd
+++ b/pg_archive/archive_remote_cmd
@@ -3,34 +3,96 @@
 set -e
 
 dst_dir="$1"
-fname="$2"
+fname_org="$2"
 ftime="$3"
+remote_compress="$4"
+pmax="$5"
+send_status="$6"
 log_dir=$(dirname "$dst_dir")
+send_dir="$log_dir"/send_status
+fname=$fname_org
+tmp_dir='/lib/init/rw/pg_recv_sb'
 
 if [ -z "$dst_dir" -o -z "$fname" ]; then
-    echo -e "usage: archive_remote_cmd DST-DIR DST-WAL-FILENAME SRC-FILE-TIMESTAMP\n" \
+    echo -e "usage: archive_remote_cmd DST-DIR DST-WAL-FILENAME SRC-FILE-TIMESTAMP REMOTE-COMPRESS PMAX SEND-STATUS\n" \
 	"\n" \
 	"DST-DIR                    - archive directory for WALs\n" \
 	"DST-WAL-FILENAME           - %f (file name)\n" \
 	"SRC-FILE-TIMESTAMP         - date and time of src WAL file in 'touch --date' format\n"
+	"REMOTE-COMPRESS            - received WAL is not compressed, compress it here\n"
+	"PMAX                       - if REMOTE-COMPRESS - use PMAX compress threads\n"
+	"SEND-STATUS                - create .new file for recieved WAL at DST-DIR/../send_status dir\n"
     exit 1
 fi
 
-if [ -f "$dst_dir"/"$fname" ]; then
-    echo "ERROR: $dst_dir/$fname already exist"
+# не перезаписываем ранее сохраненные файлы с неверным md5
+if [ -f "$tmp_dir"/"$fname_org".bad_md5 ]; then
+    echo "ERROR: $dst_dir/$fname_org already exist with different md5"
     exit 1
 fi
+
+# если такой WAL уже есть в архиве, попробовать сравнить его md5
+# это нужно при promote, так как postgres из-за недоработки
+# пытается со standby после его promote повторно отправить
+# в архив WALы, которые уже там есть с предыдущего мастера
+if [ -f "$dst_dir"/"$fname_org" ]; then
+    cat > "$tmp_dir"/"$fname_org".dup
+    md5_dup=`md5sum "$tmp_dir"/"$fname_org".dup | awk '{print $1}'`
+    if [[ $fname == ???????????????????????? && $remote_compress ]]; then
+        # возьмем оригинал из архива и распакуем для проверки md5
+        pbzip2 -d -p"$pmax" < "$dst_dir"/"$fname_org" > "$tmp_dir"/"$fname_org".org
+        md5_orig=`md5sum "$tmp_dir"/"$fname_org".org | awk '{print $1}'`
+        rm "$tmp_dir"/"$fname_org".org
+    else
+        md5_orig=`md5sum "$dst_dir"/"$fname_org" | awk '{print $1}'`
+    fi
+    if [[ $md5_orig != $md5_dup ]]; then
+        echo "ERROR: $dst_dir/$fname_org already exist with different md5"
+        # пожатый дубликат с другим md5 оставляем для анализа
+        mv "$tmp_dir"/"$fname_org".dup "$tmp_dir"/"$fname_org".bad_md5
+        touch --no-create --date "$ftime" "$tmp_dir"/"$fname_org".bad_md5 || true # ignore errors
+        exit 1
+    else
+        # если md5 совпадает, то выходим без ошибки
+        echo "WARN: $dst_dir/$fname_org already exist with same md5"
+        rm "$tmp_dir"/"$fname_org".dup
+        exit 0
+    fi
+fi
+
 if [ -f "$dst_dir"/"$fname".tmp ]; then
     echo "ERROR: $dst_dir/$fname.tmp already exist"
     exit 1
 fi
 
-echo "$fname" > "$log_dir"/LASTLOG
 # что бы не обрабатывать ошибки при восстановлении от частично прочитанного файла
 # который в данный момент ещё пишется в архив, будем создавать файл в архиве атомарно
 # через move
-cat > "$dst_dir"/"$fname".tmp
-touch --date "$ftime" "$dst_dir"/"$fname".tmp || true # ignore errors
+if [[ $fname == ???????????????????????? && $remote_compress ]]; then
+    cat > "$tmp_dir"/"$fname".new
+    size=$(stat -c '%s' "$tmp_dir"/"$fname".new)
+    if [[ $size -ne 16777216 ]]; then
+        mv "$tmp_dir"/"$fname".new "$tmp_dir"/"$fname".bad
+        echo "ERROR: $tmp_dir/$fname.bad wrong size: $size"
+        exit 1
+    fi
+    pbzip2 -1 -p"$pmax" < "$tmp_dir"/"$fname".new > "$dst_dir"/"$fname".tmp
+    rm "$tmp_dir"/"$fname".new
+else
+    cat > "$dst_dir"/"$fname".tmp
+fi
+
+touch --no-create --date "$ftime" "$dst_dir"/"$fname".tmp || true # ignore errors
 mv "$dst_dir"/"$fname".tmp "$dst_dir"/"$fname"
+
+# fsync файла и директории, в случае если установлен пакет 'coreutils-sync'
+if [ -f "/usr/local/bin/sync" ]; then
+    /usr/local/bin/sync "$dst_dir"/"$fname"
+    /usr/local/bin/sync "$dst_dir"
+fi
+
+if [[ $send_status ]]; then
+    echo -n > "$send_dir"/"$fname_org".new
+fi
 
 exit 0
